version: '3'

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ciccc-japan-strapi
    restart: always
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: development
    volumes:
      - .:/srv/app
    networks:
      - strapi-network

networks:
  strapi-network:
